{"cells":[{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"from contextlib import contextmanager\nfrom dataclasses import dataclass\nfrom typing import Callable, List, Optional, Tuple, Union, Literal","execution_count":2,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"def name_generator(f):\n    '''Just a little name generator so we can tell our things apart!'''\n    i = 0\n    while True:\n        yield f(i)\n        i += 1\nnames = name_generator(lambda n: f\"thing-{n}\")","execution_count":3,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"`MhThingy` is just a little thing to get from our context manager, that\nwill let us see how it works and how it interacts with exception handling.\n\nThe `compute()` method takes a keyword argument `fail=`, which if true,\ncauses it to raise an exception.\n\nIt also raises an exception if it is not ready. It is only ready while within\nthe context manager's scope."},{"metadata":{"trusted":true},"cell_type":"code","source":"@dataclass\nclass MyThingy:\n    name: str = next(names)\n    exception: Optional[Exception] = None\n    state: Literal['new', 'ready', 'done'] = 'new'\n    def compute(self, /, fail=False) -> int:\n        print(f'MT: compute {self}')\n        if fail:\n            raise ValueError(f\"> {self} failed\")\n        if self.state == 'ready':\n            return 42\n        else:\n            raise Exception(\"Not ready: {self}\")","execution_count":4,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"We can create an instance of MyThingy, but it won't be marked as ready, and we\nwon't know what to do to make it ready, nor unready."},{"metadata":{"trusted":true},"cell_type":"code","source":"MyThingy()","execution_count":5,"outputs":[{"output_type":"execute_result","execution_count":5,"data":{"text/plain":"MyThingy(name='thing-0', exception=None, state='new')"},"metadata":{}}]},{"metadata":{},"cell_type":"markdown","source":"Here is our context manager. There are many was to implemnt context managers, but using\na generator and the @contextmanager decorator is one of the simplest.\n\nI'll cover an even simpler one at the end. But first, let's look at a generator-based context\nmanager, how generators work."},{"metadata":{"trusted":true},"cell_type":"code","source":"@contextmanager\ndef my_context_manager():\n    print(\"Enter\")\n    try:\n        thing = MyThingy()\n        thing.state = 'ready'\n        # We don't care about the return value for yield here\n        print(\"CM: yielding {thing}\")\n        result = yield thing\n        print(\"CM: received {result}.\")\n    except Exception as ex:\n        # ContextManagers don't usually need to catch exceptions,\n        # but this helps us see what is happening.\n        print(f\"CM: got an exception: {repr(ex)}.\")\n        thing.exception = ex\n        raise ex\n    finally:\n        print(f'CM: Done with {thing}.')\n        thing.state = 'done'\n        print(\"CM: Exit\")","execution_count":6,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Let's use in a `with` statement."},{"metadata":{"trusted":true},"cell_type":"code","source":"def do_thing(*, fail: bool = False) -> MyThingy:\n    with my_context_manager() as athing:\n        value = athing.compute(fail=fail)\n        print(f\"DT: In context: {athing} => {value}\")\n    # Bad idea: using athing outside the with statement\n    print(f\"DT: Out of context: {athing}\")\n    # Worse idea: returning it!\n    return athing","execution_count":7,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Let's first call `do_thing` without an exception."},{"metadata":{"trusted":true},"cell_type":"code","source":"a_thing = do_thing()\nprint(f\"TL: Out of context: {a_thing}\")","execution_count":8,"outputs":[{"output_type":"stream","text":"Enter\nCM: yielding {thing}\nMT: compute MyThingy(name='thing-0', exception=None, state='ready')\nDT: In context: MyThingy(name='thing-0', exception=None, state='ready') => 42\nCM: received {result}.\nCM: Done with MyThingy(name='thing-0', exception=None, state='ready').\nCM: Exit\nDT: Out of context: MyThingy(name='thing-0', exception=None, state='done')\nTL: Out of context: MyThingy(name='thing-0', exception=None, state='done')\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"Let's run it again, but with `fail=True` so we can look at the flow\nwhen there's an exception:"},{"metadata":{"trusted":true},"cell_type":"code","source":"do_thing(fail=True)","execution_count":9,"outputs":[{"output_type":"stream","text":"Enter\nCM: yielding {thing}\nMT: compute MyThingy(name='thing-0', exception=None, state='ready')\nCM: got an exception: ValueError(\"> MyThingy(name='thing-0', exception=None, state='ready') failed\").\nCM: Done with MyThingy(name='thing-0', exception=ValueError(\"> MyThingy(name='thing-0', exception=None, state='ready') failed\"), state='ready').\nCM: Exit\n","name":"stdout"},{"output_type":"error","ename":"ValueError","evalue":"> MyThingy(name='thing-0', exception=None, state='ready') failed","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-9-f60fb099b3c4>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mdo_thing\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfail\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-7-c22897df3ff1>\u001b[0m in \u001b[0;36mdo_thing\u001b[0;34m(fail)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mdo_thing\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfail\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mbool\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m->\u001b[0m \u001b[0mMyThingy\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0mmy_context_manager\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mathing\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m         \u001b[0mvalue\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mathing\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcompute\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfail\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mfail\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m         \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"DT: In context: {athing} => {value}\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;31m# Bad idea: using athing outside the with statement\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m<ipython-input-4-d3ddb59f2b7a>\u001b[0m in \u001b[0;36mcompute\u001b[0;34m(self, fail)\u001b[0m\n\u001b[1;32m      7\u001b[0m         \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf'MT: compute {self}'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mfail\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 9\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34mf\"> {self} failed\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     10\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstate\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m'ready'\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     11\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0;36m42\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: > MyThingy(name='thing-0', exception=None, state='ready') failed"]}]},{"metadata":{},"cell_type":"markdown","source":"I labelled the print statements to make it easier to interpret the output:\n\n* `CM`: The context manager generatof function.\n* `MT`: The `MyThing.compute()` method.\n* `DT`: The `do_thing()` function\n* `TL`: Top level\n\nFrom our discussion yesterday, you should understand basically how the above works. So let's\nlook at how the generator is working as a context manager, with the help of the `@contextmanager` decorator.\n\nLet's copy it without the `@contextmanager` decorator."},{"metadata":{"trusted":true},"cell_type":"code","source":"def almost_context_manager():\n    print(\"Enter\")\n    try:\n        thing = MyThingy()\n        thing.state = 'ready'\n        # We don't care about the return value for yield here\n        print(\"CM: yielding {thing}\")\n        result = yield thing\n        print(\"CM: received {result}.\")\n    except Exception as ex:\n        # ContextManagers don't usually need to catch exceptions,\n        # but this helps us see what is happening.\n        print(f\"CM: got an exception: {repr(ex)}.\")\n        thing.exception = ex\n        raise ex\n    finally:\n        print(f'CM: Done with {thing}.')\n        thing.state = 'done'\n        print(\"CM: Exit\")","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"def demo(path: Literal['next', 'send', 'throw', 'end']):\n    # Before decoration, my_context_manager() returns a generator.\n    cm = almost_context_manager()\n    # From the generator, we can get an iterator\n    cm_it = iter(cm)\n    try:\n        match path:\n            case 'next':\n                ## next() is used to get the next element in\n                ## iterating, etc.\n                ## It is also used to get the object for the 'as <var>' part\n                ## of the `with` statement.\n                print(f\"Next: {next(cm_it)}\")\n            case 'send':\n                ## You can't send before the generator has yielded its first\n                ## value. (Onl value, if we're makinog a context manager)\n                print(f\"Next: {next(cm_it)}\")\n                ## send and next are two sides of the same coin. Send\n                ## gives a return value for `yield`, `next` gives the\n                ## hielded value.\n                print(f\"Send returned: {cm.send('OK')}\")\n            case 'throw':\n                # @contextmanager uses .throw(ex) to pass the exception\n                # to the generator function.\n                # After doing a `yield`, a generator is pausedd, only waking up\n                # when send or next are done.\n                # an exception to throw inside the generator\n                # This will then continue on up the stack to be handled\n                # outside (or not).\n                ex = ArithmeticError(\"the answer != 42\")\n                cm.throw(ex)\n            case 'end':\n                # Iterators throw StopIteration when next() is called\n                # and they don't have any more values.\n                print(f\"Next #1: {next(cm_it)}\")\n                print(f\"Next #2: {next(cm_it)}\")\n            case _:\n                print(f\"Invalid arg: {path}. It should be one of 'next', 'send','throw' or 'end'\")\n    except StopIteration:\n        print(\"Done iterating\")\n    except Exception as ex:\n        print(f\"We got back the error we sent: {repr(ex)}\")\n","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"demo('next')","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"demo('send')","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"demo('throw')","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"So how do we turn a generator into a context manager?\n\nA context manager just implements`__enter__` and `__exit__` methods.\n\nSo let's make a decorator!"},{"metadata":{"trusted":true},"cell_type":"code","source":"# I'll skip the type annotations to keep it simple.\nclass OurCtxMgr:\n    def __init__(self, gen):\n        print(f\"OC: Creating real context manager to wrap {gen}\")\n        self.gen = gen\n    def __enter__(self):\n        # This is what the next() function does.\n        return self.gen.__next__()\n    def __exit__(self, type, value, traceback):\n        if type is None:\n            # Let the generator continue.\n            # I use send() to illustrate, but the real\n            # code uses __next__(), bcause there's nothing\n            # useful to send\n            try:\n                self.gen.send(\"norhing useful\")\n            except StopIteration:\n                # Either way, we have to handle StopIteration.\n                print(f\"OC: Generator completed\")\n        else:\n            print(f\"C: Passing exception {value} on to generator.\")\n            try:\n                self.gen.throw(type, value, traceback)\n            except Exception as ex:\n                print(f\"OC: Generator's uncaught exception: {ex}\")\n                raise ex\ndef our_ctx_mgr(f):\n    def ctx_mgr(*args, **kwargs):\n        return OurCtxMgr(f(*args, **kwargs))\n    # Return our inner function to use in place of the supplied function.\n    return ctx_mgr","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"So let's use it to make a real context manager!"},{"metadata":{"trusted":true},"cell_type":"code","source":"@our_ctx_mgr\ndef real_context_manager():\n    print(\"Enter\")\n    try:\n        thing = MyThingy()\n        thing.state = 'ready'\n        # We don't care about the return value for yield here\n        print(f\"CM: yielding {thing}\")\n        result = yield thing\n        print(f\"CM: received {result}.\")\n    except Exception as ex:\n        # ContextManagers don't usually need to catch exceptions,\n        # but this helps us see what is happening.Z\n        print(f\"CM: got an exception: {repr(ex)}.\")\n        thing.exception = ex\n        raise ex\n    finally:\n        print(f'CM: Done with {thing}.')\n        thing.state = 'done'\n        print(\"CM: Exit\")\n        ","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"def test_our_thing(fail:bool = False):\n    with real_context_manager() as our_thing:\n        print(f\"TO: got {our_thing}\")\n        val = our_thing.compute(fail=fail)\n        print(f\"TO: Computed {val}\")\n        return our_thing # Still a bad idea!","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"test_our_thing(fail=False)","execution_count":null,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"test_our_thing(fail=True)","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"If you carefully examine that stack trace, you can see tha the generator was waiting at the `yield` statement\nfor the outside to ask for the `next` value (or `send` it one, `next` is really just `return send(None)`"},{"metadata":{},"cell_type":"markdown","source":"## An even simpler context manager\n\nI promised you earlier an even simpler context manager.\n\nFirst, let's make one little addition to `MyThing`"},{"metadata":{"trusted":true},"cell_type":"code","source":"class SimpleThing(MyThingy):\n    def close(self):\n        print(\"ST: closing {self}\")\n        self.state = 'done'\n\ndef make_ready(thing: SimpleThing):\n    match thing.state:\n        case 'new':\n            print(f\"MR: Making it ready.\")\n            thing.state = 'ready'\n            return thing\n        case 'ready':\n            return thing\n        case 'done':\n\n            raise Exception(f\"{thing} is already done\")","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Now let's see how to make a context manager out of that on the fly!"},{"metadata":{"trusted":true},"cell_type":"code","source":":from contextlib import closing\nwith closing(make_ready(SimpleThing())) as st:\n    print(f\"TL: {st} => {st.compute()}\")","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"### Bonus Round"},{"metadata":{"trusted":true},"cell_type":"code","source":"@contextmanager\ndef until_end():\n    try:\n        yield\n    except StopIteration:\n        print(\"Iteration done!\")","execution_count":16,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"it = iter((1, 2, 3))\nwith until_end():\n    while True:\n        print(next(it))","execution_count":17,"outputs":[{"output_type":"stream","text":"1\n2\n3\nIteration done!\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"Our context manager handled the exception for us!"},{"metadata":{"trusted":false},"cell_type":"markdown","source":"## Conclusion\n\nGenerators are more flexible than using `closing()`\n\n    * They handle initialization. Without them we had to introduce s `make_ready` function'\n    * They can handle exceptions more flexibly.\n    * They are consice and easy to write.\n    * They do not depend on anything about the object they expose.\n        - They only need to be able to create or locate it and yield it."}],"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3","language":"python"},"language_info":{"name":"python","version":"3.10.4","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat":4,"nbformat_minor":2}
